version: "3"
services:
  db:
    container_name: banco_homologacao
    hostname: localhost
    image: mysql:8.0
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: nt
      MYSQL_DATABASE: base_de_dados
      MYSQL_USER: alexandre_rayol
      MYSQL_PASSWORD: nt
      TZ: America/Sao_Paulo
